// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: services/network/api/src/request.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_Unknown Type = 0
	Type_POST    Type = 1
	Type_GET     Type = 2
	Type_DELETE  Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Unknown",
		1: "POST",
		2: "GET",
		3: "DELETE",
	}
	Type_value = map[string]int32{
		"Unknown": 0,
		"POST":    1,
		"GET":     2,
		"DELETE":  3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_services_network_api_src_request_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_services_network_api_src_request_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_services_network_api_src_request_proto_rawDescGZIP(), []int{0}
}

type KV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"key"
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	// @inject_tag: json:"value"
	//
	// Types that are assignable to Value:
	//	*KV_String_
	//	*KV_Float64
	//	*KV_Float32
	//	*KV_Integer
	//	*KV_Bool
	Value isKV_Value `protobuf_oneof:"Value" json:"value"`
}

func (x *KV) Reset() {
	*x = KV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_api_src_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_api_src_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_services_network_api_src_request_proto_rawDescGZIP(), []int{0}
}

func (x *KV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (m *KV) GetValue() isKV_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *KV) GetString_() string {
	if x, ok := x.GetValue().(*KV_String_); ok {
		return x.String_
	}
	return ""
}

func (x *KV) GetFloat64() float64 {
	if x, ok := x.GetValue().(*KV_Float64); ok {
		return x.Float64
	}
	return 0
}

func (x *KV) GetFloat32() float32 {
	if x, ok := x.GetValue().(*KV_Float32); ok {
		return x.Float32
	}
	return 0
}

func (x *KV) GetInteger() int64 {
	if x, ok := x.GetValue().(*KV_Integer); ok {
		return x.Integer
	}
	return 0
}

func (x *KV) GetBool() bool {
	if x, ok := x.GetValue().(*KV_Bool); ok {
		return x.Bool
	}
	return false
}

type isKV_Value interface {
	isKV_Value()
}

type KV_String_ struct {
	// @inject_tag: json:"string"
	String_ string `protobuf:"bytes,2,opt,name=String,proto3,oneof" json:"string"`
}

type KV_Float64 struct {
	// @inject_tag: json:"float64"
	Float64 float64 `protobuf:"fixed64,3,opt,name=Float64,proto3,oneof" json:"float64"`
}

type KV_Float32 struct {
	// @inject_tag: json:"float32"
	Float32 float32 `protobuf:"fixed32,4,opt,name=Float32,proto3,oneof" json:"float32"`
}

type KV_Integer struct {
	// @inject_tag: json:"integer"
	Integer int64 `protobuf:"varint,5,opt,name=Integer,proto3,oneof" json:"integer"`
}

type KV_Bool struct {
	// @inject_tag: json:"bool"
	Bool bool `protobuf:"varint,6,opt,name=Bool,proto3,oneof" json:"bool"`
}

func (*KV_String_) isKV_Value() {}

func (*KV_Float64) isKV_Value() {}

func (*KV_Float32) isKV_Value() {}

func (*KV_Integer) isKV_Value() {}

func (*KV_Bool) isKV_Value() {}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"type"
	Type Type `protobuf:"varint,1,opt,name=Type,proto3,enum=networkAPI.Type" json:"type"`
	// @inject_tag: json:"endpoint"
	Endpoint string `protobuf:"bytes,2,opt,name=Endpoint,proto3" json:"endpoint"`
	// @inject_tag: json:"params"
	Params []*KV `protobuf:"bytes,3,rep,name=Params,proto3" json:"params"`
	// @inject_tag: json:"headers"
	Headers []*KV `protobuf:"bytes,4,rep,name=Headers,proto3" json:"headers"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_api_src_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_api_src_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_services_network_api_src_request_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Unknown
}

func (x *Request) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Request) GetParams() []*KV {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Request) GetHeaders() []*KV {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"code"
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"code"`
	// @inject_tag: json:"response"
	Response string `protobuf:"bytes,2,opt,name=Response,proto3" json:"response"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_api_src_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_api_src_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_services_network_api_src_request_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_services_network_api_src_request_proto protoreflect.FileDescriptor

var file_services_network_api_src_request_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x41, 0x50, 0x49, 0x22, 0xa3, 0x01, 0x0a, 0x02, 0x4b, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a,
	0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x36, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x07, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x36, 0x34, 0x12, 0x1a, 0x0a, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x12,
	0x1a, 0x0a, 0x07, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x07, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x42,
	0x6f, 0x6f, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x42, 0x6f, 0x6f,
	0x6c, 0x42, 0x07, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x50,
	0x49, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x41, 0x50, 0x49, 0x2e, 0x4b, 0x56, 0x52, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x28, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x50, 0x49, 0x2e, 0x4b,
	0x56, 0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x3a, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x32, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x32, 0x41, 0x0a, 0x0e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x02,
	0x44, 0x6f, 0x12, 0x13, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x50, 0x49, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x41, 0x50, 0x49, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x2d, 0x76, 0x61,
	0x72, 0x6d, 0x61, 0x7a, 0x79, 0x61, 0x72, 0x2f, 0x47, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_network_api_src_request_proto_rawDescOnce sync.Once
	file_services_network_api_src_request_proto_rawDescData = file_services_network_api_src_request_proto_rawDesc
)

func file_services_network_api_src_request_proto_rawDescGZIP() []byte {
	file_services_network_api_src_request_proto_rawDescOnce.Do(func() {
		file_services_network_api_src_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_network_api_src_request_proto_rawDescData)
	})
	return file_services_network_api_src_request_proto_rawDescData
}

var file_services_network_api_src_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_network_api_src_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_network_api_src_request_proto_goTypes = []interface{}{
	(Type)(0),        // 0: networkAPI.Type
	(*KV)(nil),       // 1: networkAPI.KV
	(*Request)(nil),  // 2: networkAPI.Request
	(*Response)(nil), // 3: networkAPI.Response
}
var file_services_network_api_src_request_proto_depIdxs = []int32{
	0, // 0: networkAPI.Request.Type:type_name -> networkAPI.Type
	1, // 1: networkAPI.Request.Params:type_name -> networkAPI.KV
	1, // 2: networkAPI.Request.Headers:type_name -> networkAPI.KV
	2, // 3: networkAPI.RequestService.Do:input_type -> networkAPI.Request
	3, // 4: networkAPI.RequestService.Do:output_type -> networkAPI.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_network_api_src_request_proto_init() }
func file_services_network_api_src_request_proto_init() {
	if File_services_network_api_src_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_network_api_src_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_api_src_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_api_src_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_services_network_api_src_request_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*KV_String_)(nil),
		(*KV_Float64)(nil),
		(*KV_Float32)(nil),
		(*KV_Integer)(nil),
		(*KV_Bool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_network_api_src_request_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_network_api_src_request_proto_goTypes,
		DependencyIndexes: file_services_network_api_src_request_proto_depIdxs,
		EnumInfos:         file_services_network_api_src_request_proto_enumTypes,
		MessageInfos:      file_services_network_api_src_request_proto_msgTypes,
	}.Build()
	File_services_network_api_src_request_proto = out.File
	file_services_network_api_src_request_proto_rawDesc = nil
	file_services_network_api_src_request_proto_goTypes = nil
	file_services_network_api_src_request_proto_depIdxs = nil
}
