#default config for coinex
loadMarketsOnline: false
markets:
#  - value: BTCUSDT
#    startTime: 1606780800
#  - name: KAVAUSDT
#    startTime: 1606780800
resolutions:
  #  - value: 60
  #    label: 1min
  #    duration: 60000000000
  #  - value: 180
  #    label: 3min
  #    duration: 180000000000
  #  - value: 300
  #    label: 5min
  #    duration: 300000000000
  - value: 900
    label: 15min
    duration: 900000000000
  #  - value: 1800
  #    label: 30min
  #    duration: 1800000000000
  #  - value: 3600
  #    label: 1hour
  #    duration: 3600000000000
  #  - value: 7200
  #    label: 2hour
  #    duration: 7200000000000
  #  - value: 14400
  #    label: 4hour
  #    duration: 14400000000000
  #  - value: 21600
  #    label: 6hour
  #    duration: 21600000000000
#  - value: 43200
#    label: 12hour
#    duration: 43200000000000
#  - value: 86400
#    label: 1day
#    duration: 86400000000000
fakeTrading: false
enableTrading: false
strategy:
  hft: true
  bufferedCandleCount: 400
  indicatorUpdatePeriod: 1000000000
  minGainPercent: 1
  lossPercent: 5
  maxGainPercent: 5
indicatorConfigs:
  MovingAverageLength: 20
  MovingAverageSource: close
  BollingerLength: 20
  BollingerDeviation: 2
  MacdFastLength: 12
  MacdSlowLength: 26
  MacdSignalLength: 9
  MacdSource: close
  RsiLength: 14
  StochasticLength: 14
  StochasticSmoothK: 3
  StochasticSmoothD: 10
  AdxAtrLength: 14
  #parabolic sar
  maxAcceleration: 0.2
  Acceleration: 0.02

