// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	api "github.com/h-varmazyar/Gate/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServiceClient interface {
	Create(ctx context.Context, in *CreateMarketReq, opts ...grpc.CallOption) (*Market, error)
	Return(ctx context.Context, in *ReturnMarketRequest, opts ...grpc.CallOption) (*Market, error)
	List(ctx context.Context, in *MarketListRequest, opts ...grpc.CallOption) (*Markets, error)
	ReturnBySource(ctx context.Context, in *MarketListBySourceRequest, opts ...grpc.CallOption) (*Markets, error)
	StartWorker(ctx context.Context, in *WorkerStartReq, opts ...grpc.CallOption) (*api.Void, error)
	StopWorker(ctx context.Context, in *WorkerStopReq, opts ...grpc.CallOption) (*api.Void, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) Create(ctx context.Context, in *CreateMarketReq, opts ...grpc.CallOption) (*Market, error) {
	out := new(Market)
	err := c.cc.Invoke(ctx, "/chipmunkApi.MarketService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) Return(ctx context.Context, in *ReturnMarketRequest, opts ...grpc.CallOption) (*Market, error) {
	out := new(Market)
	err := c.cc.Invoke(ctx, "/chipmunkApi.MarketService/Return", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) List(ctx context.Context, in *MarketListRequest, opts ...grpc.CallOption) (*Markets, error) {
	out := new(Markets)
	err := c.cc.Invoke(ctx, "/chipmunkApi.MarketService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) ReturnBySource(ctx context.Context, in *MarketListBySourceRequest, opts ...grpc.CallOption) (*Markets, error) {
	out := new(Markets)
	err := c.cc.Invoke(ctx, "/chipmunkApi.MarketService/ReturnBySource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) StartWorker(ctx context.Context, in *WorkerStartReq, opts ...grpc.CallOption) (*api.Void, error) {
	out := new(api.Void)
	err := c.cc.Invoke(ctx, "/chipmunkApi.MarketService/StartWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) StopWorker(ctx context.Context, in *WorkerStopReq, opts ...grpc.CallOption) (*api.Void, error) {
	out := new(api.Void)
	err := c.cc.Invoke(ctx, "/chipmunkApi.MarketService/StopWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations should embed UnimplementedMarketServiceServer
// for forward compatibility
type MarketServiceServer interface {
	Create(context.Context, *CreateMarketReq) (*Market, error)
	Return(context.Context, *ReturnMarketRequest) (*Market, error)
	List(context.Context, *MarketListRequest) (*Markets, error)
	ReturnBySource(context.Context, *MarketListBySourceRequest) (*Markets, error)
	StartWorker(context.Context, *WorkerStartReq) (*api.Void, error)
	StopWorker(context.Context, *WorkerStopReq) (*api.Void, error)
}

// UnimplementedMarketServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMarketServiceServer struct {
}

func (UnimplementedMarketServiceServer) Create(context.Context, *CreateMarketReq) (*Market, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedMarketServiceServer) Return(context.Context, *ReturnMarketRequest) (*Market, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Return not implemented")
}
func (UnimplementedMarketServiceServer) List(context.Context, *MarketListRequest) (*Markets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedMarketServiceServer) ReturnBySource(context.Context, *MarketListBySourceRequest) (*Markets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnBySource not implemented")
}
func (UnimplementedMarketServiceServer) StartWorker(context.Context, *WorkerStartReq) (*api.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWorker not implemented")
}
func (UnimplementedMarketServiceServer) StopWorker(context.Context, *WorkerStopReq) (*api.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopWorker not implemented")
}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.MarketService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).Create(ctx, req.(*CreateMarketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_Return_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).Return(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.MarketService/Return",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).Return(ctx, req.(*ReturnMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.MarketService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).List(ctx, req.(*MarketListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_ReturnBySource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketListBySourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).ReturnBySource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.MarketService/ReturnBySource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).ReturnBySource(ctx, req.(*MarketListBySourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_StartWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerStartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).StartWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.MarketService/StartWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).StartWorker(ctx, req.(*WorkerStartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_StopWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerStopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).StopWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.MarketService/StopWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).StopWorker(ctx, req.(*WorkerStopReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chipmunkApi.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MarketService_Create_Handler,
		},
		{
			MethodName: "Return",
			Handler:    _MarketService_Return_Handler,
		},
		{
			MethodName: "List",
			Handler:    _MarketService_List_Handler,
		},
		{
			MethodName: "ReturnBySource",
			Handler:    _MarketService_ReturnBySource_Handler,
		},
		{
			MethodName: "StartWorker",
			Handler:    _MarketService_StartWorker_Handler,
		},
		{
			MethodName: "StopWorker",
			Handler:    _MarketService_StopWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/chipmunk/api/src/market.proto",
}
