// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: services/chipmunk/api/proto/src/asset.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetServiceClient interface {
	Create(ctx context.Context, in *AssetCreateReq, opts ...grpc.CallOption) (*Asset, error)
	ReturnByID(ctx context.Context, in *AssetReturnByIDReq, opts ...grpc.CallOption) (*Asset, error)
	ReturnBySymbol(ctx context.Context, in *AssetReturnBySymbolReq, opts ...grpc.CallOption) (*Asset, error)
	List(ctx context.Context, in *GetAssetListRequest, opts ...grpc.CallOption) (*Assets, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) Create(ctx context.Context, in *AssetCreateReq, opts ...grpc.CallOption) (*Asset, error) {
	out := new(Asset)
	err := c.cc.Invoke(ctx, "/chipmunkApi.AssetService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ReturnByID(ctx context.Context, in *AssetReturnByIDReq, opts ...grpc.CallOption) (*Asset, error) {
	out := new(Asset)
	err := c.cc.Invoke(ctx, "/chipmunkApi.AssetService/ReturnByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ReturnBySymbol(ctx context.Context, in *AssetReturnBySymbolReq, opts ...grpc.CallOption) (*Asset, error) {
	out := new(Asset)
	err := c.cc.Invoke(ctx, "/chipmunkApi.AssetService/ReturnBySymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) List(ctx context.Context, in *GetAssetListRequest, opts ...grpc.CallOption) (*Assets, error) {
	out := new(Assets)
	err := c.cc.Invoke(ctx, "/chipmunkApi.AssetService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations should embed UnimplementedAssetServiceServer
// for forward compatibility
type AssetServiceServer interface {
	Create(context.Context, *AssetCreateReq) (*Asset, error)
	ReturnByID(context.Context, *AssetReturnByIDReq) (*Asset, error)
	ReturnBySymbol(context.Context, *AssetReturnBySymbolReq) (*Asset, error)
	List(context.Context, *GetAssetListRequest) (*Assets, error)
}

// UnimplementedAssetServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAssetServiceServer struct {
}

func (UnimplementedAssetServiceServer) Create(context.Context, *AssetCreateReq) (*Asset, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAssetServiceServer) ReturnByID(context.Context, *AssetReturnByIDReq) (*Asset, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnByID not implemented")
}
func (UnimplementedAssetServiceServer) ReturnBySymbol(context.Context, *AssetReturnBySymbolReq) (*Asset, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnBySymbol not implemented")
}
func (UnimplementedAssetServiceServer) List(context.Context, *GetAssetListRequest) (*Assets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.AssetService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).Create(ctx, req.(*AssetCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ReturnByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetReturnByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ReturnByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.AssetService/ReturnByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ReturnByID(ctx, req.(*AssetReturnByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ReturnBySymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetReturnBySymbolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ReturnBySymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.AssetService/ReturnBySymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ReturnBySymbol(ctx, req.(*AssetReturnBySymbolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.AssetService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).List(ctx, req.(*GetAssetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chipmunkApi.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AssetService_Create_Handler,
		},
		{
			MethodName: "ReturnByID",
			Handler:    _AssetService_ReturnByID_Handler,
		},
		{
			MethodName: "ReturnBySymbol",
			Handler:    _AssetService_ReturnBySymbol_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AssetService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/chipmunk/api/proto/src/asset.proto",
}
