// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: services/chipmunk/api/proto/src/wallet.proto

package proto

import (
	context "context"
	proto "github.com/h-varmazyar/Gate/api/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalletsServiceClient is the client API for WalletsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletsServiceClient interface {
	List(ctx context.Context, in *proto.Void, opts ...grpc.CallOption) (*Wallets, error)
	StartWorker(ctx context.Context, in *StartWorkerRequest, opts ...grpc.CallOption) (*proto.Void, error)
	StopWorker(ctx context.Context, in *proto.Void, opts ...grpc.CallOption) (*proto.Void, error)
	ReturnWallet(ctx context.Context, in *ReturnWalletReq, opts ...grpc.CallOption) (*Wallet, error)
	ReturnReference(ctx context.Context, in *ReturnReferenceReq, opts ...grpc.CallOption) (*Reference, error)
}

type walletsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletsServiceClient(cc grpc.ClientConnInterface) WalletsServiceClient {
	return &walletsServiceClient{cc}
}

func (c *walletsServiceClient) List(ctx context.Context, in *proto.Void, opts ...grpc.CallOption) (*Wallets, error) {
	out := new(Wallets)
	err := c.cc.Invoke(ctx, "/chipmunkApi.WalletsService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletsServiceClient) StartWorker(ctx context.Context, in *StartWorkerRequest, opts ...grpc.CallOption) (*proto.Void, error) {
	out := new(proto.Void)
	err := c.cc.Invoke(ctx, "/chipmunkApi.WalletsService/StartWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletsServiceClient) StopWorker(ctx context.Context, in *proto.Void, opts ...grpc.CallOption) (*proto.Void, error) {
	out := new(proto.Void)
	err := c.cc.Invoke(ctx, "/chipmunkApi.WalletsService/StopWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletsServiceClient) ReturnWallet(ctx context.Context, in *ReturnWalletReq, opts ...grpc.CallOption) (*Wallet, error) {
	out := new(Wallet)
	err := c.cc.Invoke(ctx, "/chipmunkApi.WalletsService/ReturnWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletsServiceClient) ReturnReference(ctx context.Context, in *ReturnReferenceReq, opts ...grpc.CallOption) (*Reference, error) {
	out := new(Reference)
	err := c.cc.Invoke(ctx, "/chipmunkApi.WalletsService/ReturnReference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletsServiceServer is the server API for WalletsService service.
// All implementations should embed UnimplementedWalletsServiceServer
// for forward compatibility
type WalletsServiceServer interface {
	List(context.Context, *proto.Void) (*Wallets, error)
	StartWorker(context.Context, *StartWorkerRequest) (*proto.Void, error)
	StopWorker(context.Context, *proto.Void) (*proto.Void, error)
	ReturnWallet(context.Context, *ReturnWalletReq) (*Wallet, error)
	ReturnReference(context.Context, *ReturnReferenceReq) (*Reference, error)
}

// UnimplementedWalletsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWalletsServiceServer struct {
}

func (UnimplementedWalletsServiceServer) List(context.Context, *proto.Void) (*Wallets, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedWalletsServiceServer) StartWorker(context.Context, *StartWorkerRequest) (*proto.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWorker not implemented")
}
func (UnimplementedWalletsServiceServer) StopWorker(context.Context, *proto.Void) (*proto.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopWorker not implemented")
}
func (UnimplementedWalletsServiceServer) ReturnWallet(context.Context, *ReturnWalletReq) (*Wallet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnWallet not implemented")
}
func (UnimplementedWalletsServiceServer) ReturnReference(context.Context, *ReturnReferenceReq) (*Reference, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnReference not implemented")
}

// UnsafeWalletsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletsServiceServer will
// result in compilation errors.
type UnsafeWalletsServiceServer interface {
	mustEmbedUnimplementedWalletsServiceServer()
}

func RegisterWalletsServiceServer(s grpc.ServiceRegistrar, srv WalletsServiceServer) {
	s.RegisterService(&WalletsService_ServiceDesc, srv)
}

func _WalletsService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.WalletsService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServiceServer).List(ctx, req.(*proto.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletsService_StartWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServiceServer).StartWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.WalletsService/StartWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServiceServer).StartWorker(ctx, req.(*StartWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletsService_StopWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServiceServer).StopWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.WalletsService/StopWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServiceServer).StopWorker(ctx, req.(*proto.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletsService_ReturnWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServiceServer).ReturnWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.WalletsService/ReturnWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServiceServer).ReturnWallet(ctx, req.(*ReturnWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletsService_ReturnReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnReferenceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServiceServer).ReturnReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chipmunkApi.WalletsService/ReturnReference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServiceServer).ReturnReference(ctx, req.(*ReturnReferenceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletsService_ServiceDesc is the grpc.ServiceDesc for WalletsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chipmunkApi.WalletsService",
	HandlerType: (*WalletsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _WalletsService_List_Handler,
		},
		{
			MethodName: "StartWorker",
			Handler:    _WalletsService_StartWorker_Handler,
		},
		{
			MethodName: "StopWorker",
			Handler:    _WalletsService_StopWorker_Handler,
		},
		{
			MethodName: "ReturnWallet",
			Handler:    _WalletsService_ReturnWallet_Handler,
		},
		{
			MethodName: "ReturnReference",
			Handler:    _WalletsService_ReturnReference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/chipmunk/api/proto/src/wallet.proto",
}
