// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: services/telegramBot/api/src/app.proto

package api

import (
	api "github.com/h-varmazyar/Gate/api/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"chat_id"
	ChatID int64 `protobuf:"varint,1,opt,name=ChatID,proto3" json:"chat_id"`
	// @inject_tag: json:"reply_to"
	ReplyTo int32 `protobuf:"varint,2,opt,name=ReplyTo,proto3" json:"reply_to"`
	// @inject_tag: json:"text"
	Text string `protobuf:"bytes,3,opt,name=Text,proto3" json:"text"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_telegramBot_api_src_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_services_telegramBot_api_src_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_services_telegramBot_api_src_app_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetChatID() int64 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

func (x *Message) GetReplyTo() int32 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_services_telegramBot_api_src_app_proto protoreflect.FileDescriptor

var file_services_telegramBot_api_src_app_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x67,
	0x72, 0x61, 0x6d, 0x42, 0x6f, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61,
	0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x6f, 0x74, 0x41, 0x70, 0x69,
	0x1a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x69, 0x73, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x54, 0x65, 0x78, 0x74, 0x32, 0x74, 0x0a, 0x0a, 0x42, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x09, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x09, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x12, 0x29, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0f, 0x2e, 0x62, 0x6f, 0x74, 0x41, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x2d, 0x76, 0x61, 0x72, 0x6d,
	0x61, 0x7a, 0x79, 0x61, 0x72, 0x2f, 0x47, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x6f, 0x74, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_telegramBot_api_src_app_proto_rawDescOnce sync.Once
	file_services_telegramBot_api_src_app_proto_rawDescData = file_services_telegramBot_api_src_app_proto_rawDesc
)

func file_services_telegramBot_api_src_app_proto_rawDescGZIP() []byte {
	file_services_telegramBot_api_src_app_proto_rawDescOnce.Do(func() {
		file_services_telegramBot_api_src_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_telegramBot_api_src_app_proto_rawDescData)
	})
	return file_services_telegramBot_api_src_app_proto_rawDescData
}

var file_services_telegramBot_api_src_app_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_services_telegramBot_api_src_app_proto_goTypes = []interface{}{
	(*Message)(nil),  // 0: botApi.Message
	(*api.Void)(nil), // 1: api.Void
}
var file_services_telegramBot_api_src_app_proto_depIdxs = []int32{
	1, // 0: botApi.BotService.Start:input_type -> api.Void
	1, // 1: botApi.BotService.Stop:input_type -> api.Void
	0, // 2: botApi.BotService.SendMessage:input_type -> botApi.Message
	1, // 3: botApi.BotService.Start:output_type -> api.Void
	1, // 4: botApi.BotService.Stop:output_type -> api.Void
	1, // 5: botApi.BotService.SendMessage:output_type -> api.Void
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_telegramBot_api_src_app_proto_init() }
func file_services_telegramBot_api_src_app_proto_init() {
	if File_services_telegramBot_api_src_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_telegramBot_api_src_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_telegramBot_api_src_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_telegramBot_api_src_app_proto_goTypes,
		DependencyIndexes: file_services_telegramBot_api_src_app_proto_depIdxs,
		MessageInfos:      file_services_telegramBot_api_src_app_proto_msgTypes,
	}.Build()
	File_services_telegramBot_api_src_app_proto = out.File
	file_services_telegramBot_api_src_app_proto_rawDesc = nil
	file_services_telegramBot_api_src_app_proto_goTypes = nil
	file_services_telegramBot_api_src_app_proto_depIdxs = nil
}
