// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.6.1
// source: services/eagle/api/src/indicators.proto

package api

import (
	context "context"
	api "github.com/mrNobody95/Gate/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IndicatorsServiceClient is the client API for IndicatorsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndicatorsServiceClient interface {
	NewWorker(ctx context.Context, in *AddWorkerRequest, opts ...grpc.CallOption) (*api.Void, error)
	CancelWorker(ctx context.Context, in *CancelWorkerRequest, opts ...grpc.CallOption) (*api.Void, error)
}

type indicatorsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndicatorsServiceClient(cc grpc.ClientConnInterface) IndicatorsServiceClient {
	return &indicatorsServiceClient{cc}
}

func (c *indicatorsServiceClient) NewWorker(ctx context.Context, in *AddWorkerRequest, opts ...grpc.CallOption) (*api.Void, error) {
	out := new(api.Void)
	err := c.cc.Invoke(ctx, "/eagleApi.indicatorsService/NewWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indicatorsServiceClient) CancelWorker(ctx context.Context, in *CancelWorkerRequest, opts ...grpc.CallOption) (*api.Void, error) {
	out := new(api.Void)
	err := c.cc.Invoke(ctx, "/eagleApi.indicatorsService/CancelWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndicatorsServiceServer is the server API for IndicatorsService service.
// All implementations should embed UnimplementedIndicatorsServiceServer
// for forward compatibility
type IndicatorsServiceServer interface {
	NewWorker(context.Context, *AddWorkerRequest) (*api.Void, error)
	CancelWorker(context.Context, *CancelWorkerRequest) (*api.Void, error)
}

// UnimplementedIndicatorsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedIndicatorsServiceServer struct {
}

func (UnimplementedIndicatorsServiceServer) NewWorker(context.Context, *AddWorkerRequest) (*api.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewWorker not implemented")
}
func (UnimplementedIndicatorsServiceServer) CancelWorker(context.Context, *CancelWorkerRequest) (*api.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelWorker not implemented")
}

// UnsafeIndicatorsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndicatorsServiceServer will
// result in compilation errors.
type UnsafeIndicatorsServiceServer interface {
	mustEmbedUnimplementedIndicatorsServiceServer()
}

func RegisterIndicatorsServiceServer(s grpc.ServiceRegistrar, srv IndicatorsServiceServer) {
	s.RegisterService(&IndicatorsService_ServiceDesc, srv)
}

func _IndicatorsService_NewWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndicatorsServiceServer).NewWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eagleApi.indicatorsService/NewWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndicatorsServiceServer).NewWorker(ctx, req.(*AddWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndicatorsService_CancelWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndicatorsServiceServer).CancelWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eagleApi.indicatorsService/CancelWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndicatorsServiceServer).CancelWorker(ctx, req.(*CancelWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndicatorsService_ServiceDesc is the grpc.ServiceDesc for IndicatorsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndicatorsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eagleApi.indicatorsService",
	HandlerType: (*IndicatorsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewWorker",
			Handler:    _IndicatorsService_NewWorker_Handler,
		},
		{
			MethodName: "CancelWorker",
			Handler:    _IndicatorsService_CancelWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/eagle/api/src/indicators.proto",
}
