// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: services/eagle/api/src/signals.proto

package api

import (
	api "github.com/h-varmazyar/Gate/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddSignalsWorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"resolution"
	Resolution *api.Resolution `protobuf:"bytes,1,opt,name=Resolution,proto3" json:"resolution"`
	// @inject_tag: json:"market"
	Market *api.Market `protobuf:"bytes,2,opt,name=Market,proto3" json:"market"`
}

func (x *AddSignalsWorkerRequest) Reset() {
	*x = AddSignalsWorkerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_eagle_api_src_signals_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSignalsWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSignalsWorkerRequest) ProtoMessage() {}

func (x *AddSignalsWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_eagle_api_src_signals_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSignalsWorkerRequest.ProtoReflect.Descriptor instead.
func (*AddSignalsWorkerRequest) Descriptor() ([]byte, []int) {
	return file_services_eagle_api_src_signals_proto_rawDescGZIP(), []int{0}
}

func (x *AddSignalsWorkerRequest) GetResolution() *api.Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *AddSignalsWorkerRequest) GetMarket() *api.Market {
	if x != nil {
		return x.Market
	}
	return nil
}

type CancelSignalsWorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"resolution_id"
	ResolutionID string `protobuf:"bytes,1,opt,name=ResolutionID,proto3" json:"resolution_id"`
	// @inject_tag: json:"market_id"
	MarketID string `protobuf:"bytes,2,opt,name=MarketID,proto3" json:"market_id"`
}

func (x *CancelSignalsWorkerRequest) Reset() {
	*x = CancelSignalsWorkerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_eagle_api_src_signals_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelSignalsWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSignalsWorkerRequest) ProtoMessage() {}

func (x *CancelSignalsWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_eagle_api_src_signals_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSignalsWorkerRequest.ProtoReflect.Descriptor instead.
func (*CancelSignalsWorkerRequest) Descriptor() ([]byte, []int) {
	return file_services_eagle_api_src_signals_proto_rawDescGZIP(), []int{1}
}

func (x *CancelSignalsWorkerRequest) GetResolutionID() string {
	if x != nil {
		return x.ResolutionID
	}
	return ""
}

func (x *CancelSignalsWorkerRequest) GetMarketID() string {
	if x != nil {
		return x.MarketID
	}
	return ""
}

var File_services_eagle_api_src_signals_proto protoreflect.FileDescriptor

var file_services_eagle_api_src_signals_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x65, 0x61, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x61, 0x67, 0x6c, 0x65, 0x41, 0x70, 0x69,
	0x1a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x69, 0x73, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x17, 0x41, 0x64,
	0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x22, 0x5c, 0x0a, 0x1a, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x32, 0x8c, 0x01, 0x0a, 0x0e, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x09,
	0x4e, 0x65, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x65, 0x61, 0x67, 0x6c,
	0x65, 0x41, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x3f, 0x0a, 0x0c, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x65, 0x61, 0x67, 0x6c, 0x65, 0x41,
	0x70, 0x69, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x72, 0x4e, 0x6f, 0x62, 0x6f, 0x64, 0x79, 0x39,
	0x35, 0x2f, 0x47, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x65, 0x61, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_services_eagle_api_src_signals_proto_rawDescOnce sync.Once
	file_services_eagle_api_src_signals_proto_rawDescData = file_services_eagle_api_src_signals_proto_rawDesc
)

func file_services_eagle_api_src_signals_proto_rawDescGZIP() []byte {
	file_services_eagle_api_src_signals_proto_rawDescOnce.Do(func() {
		file_services_eagle_api_src_signals_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_eagle_api_src_signals_proto_rawDescData)
	})
	return file_services_eagle_api_src_signals_proto_rawDescData
}

var file_services_eagle_api_src_signals_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_eagle_api_src_signals_proto_goTypes = []interface{}{
	(*AddSignalsWorkerRequest)(nil),    // 0: eagleApi.AddSignalsWorkerRequest
	(*CancelSignalsWorkerRequest)(nil), // 1: eagleApi.CancelSignalsWorkerRequest
	(*api.Resolution)(nil),             // 2: api.Resolution
	(*api.Market)(nil),                 // 3: api.Market
	(*api.Void)(nil),                   // 4: api.Void
}
var file_services_eagle_api_src_signals_proto_depIdxs = []int32{
	2, // 0: eagleApi.AddSignalsWorkerRequest.Resolution:type_name -> api.Resolution
	3, // 1: eagleApi.AddSignalsWorkerRequest.Market:type_name -> api.Market
	0, // 2: eagleApi.signalsService.NewWorker:input_type -> eagleApi.AddSignalsWorkerRequest
	1, // 3: eagleApi.signalsService.CancelWorker:input_type -> eagleApi.CancelSignalsWorkerRequest
	4, // 4: eagleApi.signalsService.NewWorker:output_type -> api.Void
	4, // 5: eagleApi.signalsService.CancelWorker:output_type -> api.Void
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_eagle_api_src_signals_proto_init() }
func file_services_eagle_api_src_signals_proto_init() {
	if File_services_eagle_api_src_signals_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_eagle_api_src_signals_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSignalsWorkerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_eagle_api_src_signals_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelSignalsWorkerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_eagle_api_src_signals_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_eagle_api_src_signals_proto_goTypes,
		DependencyIndexes: file_services_eagle_api_src_signals_proto_depIdxs,
		MessageInfos:      file_services_eagle_api_src_signals_proto_msgTypes,
	}.Build()
	File_services_eagle_api_src_signals_proto = out.File
	file_services_eagle_api_src_signals_proto_rawDesc = nil
	file_services_eagle_api_src_signals_proto_goTypes = nil
	file_services_eagle_api_src_signals_proto_depIdxs = nil
}
