version: '3.9'

services:
  chipmunk:
    container_name: gate-chipmunk
    image: docker.iranserver.com/gatec/chipmunk:${VERSION}
    volumes:
      - ./configs/chipmunk.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  core:
    container_name: gate-core
    image: docker.iranserver.com/gatec/core:${VERSION}
    volumes:
      - ./configs/core.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  eagle:
    container_name: gate-eagle
    image: docker.iranserver.com/gatec/eagle:${VERSION}
    volumes:
      - ./configs/eagle.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  gather:
    container_name: gate-gather
    image: docker.iranserver.com/gatec/gather:${VERSION}
    volumes:
      - ./configs/gather.env:/app/.env
    network_mode: "service:proxy-router"
    depends_on:
      - postgres
      - redis
      - nats
      - proxy-router
    restart: always

  indicators:
    container_name: gate-indicators
    image: docker.iranserver.com/gatec/indicators:${VERSION}
    volumes:
      - ./configs/indicators.env:/app/.env
    networks:
      - gate
    depends_on:
      - postgres
      - redis
      - nats
    restart: always

  network:
    container_name: gate-network
    image: docker.iranserver.com/gatec/network:${VERSION}
    volumes:
      - ./configs/network.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  raven:
    container_name: gate-raven
    image: docker.iranserver.com/gatec/raven:${VERSION}
    volumes:
      - ./configs/raven.yaml:/app/configs/config.yaml
    ports:
      - 3030:8080
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  telegram_bot:
    container_name: gate-telegram_bot
    image: docker.iranserver.com/gatec/telegram_bot:${VERSION}
    volumes:
      - ./configs/telegramBot.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

