version: '3.9'

services:
  nats:
    container_name: gate-nats-server
    image: docker.iranserver.com/nats:latest
    ports:
      - "8321:4222" # Port for client connections
      - "8322:8222" # Port for monitoring (optional)
    environment:
      - NATS_MAX_PAYLOAD=10MB # Optional: Increase max payload size
    networks:
      - gate
    restart: always

  postgres:
    container_name: gate-postgres
    image: docker.iranserver.com/postgres:17
    env_file:
      - ./configs/postgres.env
    volumes:
      - gate_postgres_data:/var/lib/postgresql/data
    networks:
      - gate
    ports:
      - "8340:5432"
    restart: always

  redis:
    container_name: gate-redis
    image: docker.iranserver.com/bitnami/redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - gate_redis_data:/var/lib/redis
    networks:
      - gate
    ports:
      - "8360:6379"
    restart: always

  rabbitmq:
    container_name: gate-rabbitmq
    image: docker.iranserver.com/rabbitmq:3.8-management
    env_file:
      - ./configs/rabbit.env
    volumes:
      - gate_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gate
    ports:
      - "8350:15672"
      - "8351:5672"
    restart: always

  hysteria:
    container_name: gate-hysteria
    image: docker.iranserver.com/gatec/hysteria:${VERSION}
    volumes:
      - ./configs/hysteria.yaml:/etc/hysteria/config.yaml:ro
#    ports:
#      - "1080:1080"  # expose SOCKS5 port
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    restart: always
    networks:
      gate:
        ipv4_address: 172.28.0.102

  chipmunk:
    container_name: gate-chipmunk
    image: docker.iranserver.com/gatec/chipmunk:${VERSION}
    volumes:
      - ./configs/chipmunk.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  core:
    container_name: gate-core
    image: docker.iranserver.com/gatec/core:${VERSION}
    volumes:
      - ./configs/core.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  eagle:
    container_name: gate-eagle
    image: docker.iranserver.com/gatec/eagle:${VERSION}
    volumes:
      - ./configs/eagle.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  gather:
    container_name: gate-gather
    image: docker.iranserver.com/gatec/gather:${VERSION}
    volumes:
      - ./configs/gather.env:/app/.env
    networks:
      - gate
    depends_on:
      - postgres
      - nats
    restart: always

  indicators:
    container_name: gate-indicators
    image: docker.iranserver.com/gatec/indicators:${VERSION}
    volumes:
      - ./configs/indicators.env:/app/.env
    networks:
      - gate
    depends_on:
      - postgres
      - redis
      - nats
    restart: always

  network:
    container_name: gate-network
    image: docker.iranserver.com/gatec/network:${VERSION}
    volumes:
      - ./configs/network.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  raven:
    container_name: gate-raven
    image: docker.iranserver.com/gatec/raven:${VERSION}
    volumes:
      - ./configs/raven.yaml:/app/configs/config.yaml
    ports:
      - 3030:8080
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  telegram_bot:
    container_name: gate-telegram_bot
    image: docker.iranserver.com/gatec/telegram_bot:${VERSION}
    volumes:
      - ./configs/telegramBot.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  gate_postgres_data:
  gate_redis_data:
  gate_rabbitmq_data:


networks:
  gate:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
