version: '3.9'

networks:
  gate:
    external: true

services:
  nats:
    container_name: gate-nats-server
    image: docker.iranserver.com/nats:latest
    ports:
      - "4222:4222" # Port for client connections
      - "8222:8222" # Port for monitoring (optional)
    environment:
      - NATS_MAX_PAYLOAD=10MB # Optional: Increase max payload size
    networks:
      - gate
    restart: always

  postgres:
    container_name: gate-postgres
    image: docker.iranserver.com/postgres:17
    env_file:
      - ./configs/postgres.env
    volumes:
      - postgres_gate_data:/var/lib/postgresql/data
    networks:
      - gate
    ports:
      - "8340:5432"
    restart: always

  redis:
    container_name: gate-redis
    image: docker.iranserver.com/bitnami/redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis_gate_data:/var/lib/redis
    networks:
      - gate
    ports:
      - "8360:6379"
    restart: always

  rabbitmq:
    container_name: gate-rabbitmq
    image: docker.iranserver.com/rabbitmq:3.8-management
    env_file:
      - ./configs/rabbit.env
    volumes:
      - rabbitmq_gate_data:/var/lib/rabbitmq
    networks:
      - gate
    ports:
      - "8350:15672"
      - "8351:5672"
    restart: always

  chipmunk:
    container_name: gate-chipmunk
    image: docker.iranserver.com/gatec/chipmunk:${VERSION}
    volumes:
      - ./configs/chipmunk.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  core:
    container_name: gate-core
    image: docker.iranserver.com/gatec/core:${VERSION}
    volumes:
      - ./configs/core.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  eagle:
    container_name: gate-eagle
    image: docker.iranserver.com/gatec/eagle:${VERSION}
    volumes:
      - ./configs/eagle.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  gather:
    container_name: gate-gather
    image: docker.iranserver.com/gatec/gather:${VERSION}
    volumes:
      - ./configs/gather.env:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  indicators:
    container_name: gate-indicators
    image: docker.iranserver.com/gatec/indicators:${VERSION}
    volumes:
      - ./configs/indicators.env:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  network:
    container_name: gate-network
    image: docker.iranserver.com/gatec/network:${VERSION}
    volumes:
      - ./configs/network.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  raven:
    container_name: gate-raven
    image: docker.iranserver.com/gatec/raven:${VERSION}
    volumes:
      - ./configs/raven.yaml:/app/configs/config.yaml
    ports:
      - 3030:8080
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  telegram_bot:
    container_name: gate-telegram_bot
    image: docker.iranserver.com/gatec/telegram_bot:${VERSION}
    volumes:
      - ./configs/telegramBot.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres_gate_data:
  redis_gate_data:
  rabbitmq_gate_data:
