version: '3.9'

services:
  nats:
    container_name: gate-nats-server
    image: nats:latest
    ports:
      - "8321:4222" # Port for client connections
      - "8322:8222" # Port for monitoring (optional)
    environment:
      - NATS_MAX_PAYLOAD=10MB # Optional: Increase max payload size
    networks:
      - gate
    restart: always

  postgres:
    container_name: gate-postgres
    image: postgres:17
    env_file:
      - ./configs/postgres.env
    volumes:
      - gate_postgres_data:/var/lib/postgresql/data
    networks:
      - gate
    ports:
      - "8340:5432"
    restart: always

  redis:
    container_name: gate-redis
    image: bitnami/redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - gate_redis_data:/var/lib/redis
    networks:
      - gate
    ports:
      - "8360:6379"
    restart: always

  rabbitmq:
    container_name: gate-rabbitmq
    image: rabbitmq:3.8-management
    env_file:
      - ./configs/rabbit.env
    volumes:
      - gate_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gate
    ports:
      - "8350:15672"
      - "8351:5672"
    restart: always

  hysteria:
    container_name: gate-hysteria
    image: gatec/hysteria:${VERSION}
    volumes:
      - ./configs/hysteria.yaml:/etc/hysteria/config.yaml:ro
    ports:
      - "8390:1080"  # expose SOCKS5 port
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      gate:
        ipv4_address: 172.28.0.102


volumes:
  gate_postgres_data:
  gate_redis_data:
  gate_rabbitmq_data:


networks:
  gate:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

