version: '3.7'

networks:
  gate:
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_gate_data:/var/lib/postgresql/data
    networks:
      - gate
    ports:
      - 5432:5432
    restart: always

  redis:
    container_name: redis
    image: bitnami/redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis_gate_data:/var/lib/redis
    networks:
      - gate
    ports:
      - 6379:6379
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_gate_data:/var/lib/rabbitmq
    networks:
      - gate
    ports:
      - 15672:15672
      - 5672:5672
    restart: always

  chipmunk:
    container_name: chipmunk
    image: gatec/chipmunk:${VERSION}
    volumes:
      - /srv/configs/chipmunk/app.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  core:
    container_name: core
    image: gatec/core:${VERSION}
    volumes:
      - /srv/configs/core/app.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  eagle:
    container_name: eagle
    image: gatec/eagle:${VERSION}
    volumes:
      - /srv/configs/eagle/app.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  raven:
    container_name: raven
    image: gatec/raven:${VERSION}
    volumes:
      - /srv/configs/raven/app.yaml:/app/configs/config.yaml
    ports:
      - 3030:8080
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  network:
    container_name: network
    image: gatec/network:${VERSION}
    volumes:
      - /srv/configs/network/app.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

  telegram_bot:
    container_name: telegram_bot
    image: gatec/telegram_bot:${VERSION}
    volumes:
      - /srv/configs/telegramBot/app.yaml:/app/configs/config.yaml
    networks:
      - gate
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres_gate_data:
  redis_gate_data:
  rabbitmq_gate_data:
