create table assets
(
    id         bigint generated by default as identity primary key,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    name       text,
    symbol     text unique
);

alter table assets
    owner to postgres;

create index idx_assets_deleted_at on assets (deleted_at);
