create table markets
(
    id                             bigint generated by default as identity primary key,
    created_at                     timestamp with time zone,
    updated_at                     timestamp with time zone,
    deleted_at                     timestamp with time zone,
    name                           text unique,
    base_currency_precision        numeric,
    quote_currency_precision       numeric,
    quote_currency_id              bigint
        constraint fk_markets_quote references assets,
    base_currency_id               bigint
        constraint fk_markets_base references assets,
    taker_fee_rate                 numeric,
    maker_fee_rate                 numeric,
    min_amount                     numeric,
    is_amm_available               boolean,
    is_margin_available            boolean,
    is_premarket_trading_available boolean,
    status                         text,
    issue_date                     timestamp with time zone
);

create index idx_markets_deleted_at
    on markets (deleted_at);