// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: services/brokerage/api/src/asset.proto

package api

import (
	api "github.com/mrNobody95/Gate/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"name"`
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_asset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_asset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_asset_proto_rawDescGZIP(), []int{0}
}

func (x *GetAssetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAssetListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"page"
	Page int32 `protobuf:"varint,1,opt,name=Page,proto3" json:"page"`
}

func (x *GetAssetListRequest) Reset() {
	*x = GetAssetListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_asset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetListRequest) ProtoMessage() {}

func (x *GetAssetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_asset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetListRequest.ProtoReflect.Descriptor instead.
func (*GetAssetListRequest) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_asset_proto_rawDescGZIP(), []int{1}
}

func (x *GetAssetListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

var File_services_brokerage_api_src_asset_proto protoreflect.FileDescriptor

var file_services_brokerage_api_src_asset_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x1a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x6d, 0x69, 0x73, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61,
	0x67, 0x65, 0x32, 0x9c, 0x01, 0x0a, 0x0c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x0a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x12, 0x36, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x36, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x21, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x72, 0x4e, 0x6f, 0x62, 0x6f, 0x64, 0x79, 0x39, 0x35, 0x2f, 0x47, 0x61, 0x74, 0x65, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_brokerage_api_src_asset_proto_rawDescOnce sync.Once
	file_services_brokerage_api_src_asset_proto_rawDescData = file_services_brokerage_api_src_asset_proto_rawDesc
)

func file_services_brokerage_api_src_asset_proto_rawDescGZIP() []byte {
	file_services_brokerage_api_src_asset_proto_rawDescOnce.Do(func() {
		file_services_brokerage_api_src_asset_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_brokerage_api_src_asset_proto_rawDescData)
	})
	return file_services_brokerage_api_src_asset_proto_rawDescData
}

var file_services_brokerage_api_src_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_brokerage_api_src_asset_proto_goTypes = []interface{}{
	(*GetAssetRequest)(nil),     // 0: brokerageApi.GetAssetRequest
	(*GetAssetListRequest)(nil), // 1: brokerageApi.GetAssetListRequest
	(*api.Asset)(nil),           // 2: api.Asset
	(*api.Void)(nil),            // 3: api.Void
	(*api.Assets)(nil),          // 4: api.Assets
}
var file_services_brokerage_api_src_asset_proto_depIdxs = []int32{
	2, // 0: brokerageApi.AssetService.Set:input_type -> api.Asset
	0, // 1: brokerageApi.AssetService.GetByName:input_type -> brokerageApi.GetAssetRequest
	1, // 2: brokerageApi.AssetService.List:input_type -> brokerageApi.GetAssetListRequest
	3, // 3: brokerageApi.AssetService.Set:output_type -> api.Void
	2, // 4: brokerageApi.AssetService.GetByName:output_type -> api.Asset
	4, // 5: brokerageApi.AssetService.List:output_type -> api.Assets
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_brokerage_api_src_asset_proto_init() }
func file_services_brokerage_api_src_asset_proto_init() {
	if File_services_brokerage_api_src_asset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_brokerage_api_src_asset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_brokerage_api_src_asset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_brokerage_api_src_asset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_brokerage_api_src_asset_proto_goTypes,
		DependencyIndexes: file_services_brokerage_api_src_asset_proto_depIdxs,
		MessageInfos:      file_services_brokerage_api_src_asset_proto_msgTypes,
	}.Build()
	File_services_brokerage_api_src_asset_proto = out.File
	file_services_brokerage_api_src_asset_proto_rawDesc = nil
	file_services_brokerage_api_src_asset_proto_goTypes = nil
	file_services_brokerage_api_src_asset_proto_depIdxs = nil
}
