// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: services/brokerage/api/src/brokerage.proto

package api

import (
	api "github.com/mrNobody95/Gate/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Names int32

const (
	Names_UnknownBrokerage Names = 0
	Names_Coinex           Names = 1
)

// Enum value maps for Names.
var (
	Names_name = map[int32]string{
		0: "UnknownBrokerage",
		1: "Coinex",
	}
	Names_value = map[string]int32{
		"UnknownBrokerage": 0,
		"Coinex":           1,
	}
)

func (x Names) Enum() *Names {
	p := new(Names)
	*p = x
	return p
}

func (x Names) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Names) Descriptor() protoreflect.EnumDescriptor {
	return file_services_brokerage_api_src_brokerage_proto_enumTypes[0].Descriptor()
}

func (Names) Type() protoreflect.EnumType {
	return &file_services_brokerage_api_src_brokerage_proto_enumTypes[0]
}

func (x Names) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Names.Descriptor instead.
func (Names) EnumDescriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_brokerage_proto_rawDescGZIP(), []int{0}
}

type Brokerage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`
	// @inject_tag: json:"auth"
	Auth *api.Auth `protobuf:"bytes,2,opt,name=Auth,proto3" json:"auth"`
	// @inject_tag: json:"name"
	Name Names `protobuf:"varint,3,opt,name=Name,proto3,enum=brokerageApi.Names" json:"name"`
	// @inject_tag: json:"status"
	Status api.StatusType `protobuf:"varint,4,opt,name=Status,proto3,enum=api.StatusType" json:"status"`
}

func (x *Brokerage) Reset() {
	*x = Brokerage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_brokerage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Brokerage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brokerage) ProtoMessage() {}

func (x *Brokerage) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_brokerage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brokerage.ProtoReflect.Descriptor instead.
func (*Brokerage) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_brokerage_proto_rawDescGZIP(), []int{0}
}

func (x *Brokerage) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Brokerage) GetAuth() *api.Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Brokerage) GetName() Names {
	if x != nil {
		return x.Name
	}
	return Names_UnknownBrokerage
}

func (x *Brokerage) GetStatus() api.StatusType {
	if x != nil {
		return x.Status
	}
	return api.StatusType(0)
}

type GetBrokerage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`
	// @inject_tag: json:"auth_type"
	AuthType string `protobuf:"bytes,2,opt,name=AuthType,proto3" json:"auth_type"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,3,opt,name=Name,proto3" json:"name"`
	// @inject_tag: json:"status"
	Status string `protobuf:"bytes,4,opt,name=Status,proto3" json:"status"`
}

func (x *GetBrokerage) Reset() {
	*x = GetBrokerage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_brokerage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBrokerage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrokerage) ProtoMessage() {}

func (x *GetBrokerage) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_brokerage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrokerage.ProtoReflect.Descriptor instead.
func (*GetBrokerage) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_brokerage_proto_rawDescGZIP(), []int{1}
}

func (x *GetBrokerage) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetBrokerage) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *GetBrokerage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBrokerage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BrokerageIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`
}

func (x *BrokerageIDReq) Reset() {
	*x = BrokerageIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_brokerage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerageIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerageIDReq) ProtoMessage() {}

func (x *BrokerageIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_brokerage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerageIDReq.ProtoReflect.Descriptor instead.
func (*BrokerageIDReq) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_brokerage_proto_rawDescGZIP(), []int{2}
}

func (x *BrokerageIDReq) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_services_brokerage_api_src_brokerage_proto protoreflect.FileDescriptor

var file_services_brokerage_api_src_brokerage_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x1a, 0x12, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x6d, 0x69, 0x73, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c,
	0x01, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1d, 0x0a, 0x04,
	0x41, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x27, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x66, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x2a, 0x29, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x10, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x6f, 0x69, 0x6e, 0x65, 0x78,
	0x10, 0x01, 0x32, 0xf6, 0x01, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x17,
	0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x42, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x3f, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x41, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67,
	0x65, 0x12, 0x31, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x72, 0x4e, 0x6f, 0x62, 0x6f,
	0x64, 0x79, 0x39, 0x35, 0x2f, 0x47, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_brokerage_api_src_brokerage_proto_rawDescOnce sync.Once
	file_services_brokerage_api_src_brokerage_proto_rawDescData = file_services_brokerage_api_src_brokerage_proto_rawDesc
)

func file_services_brokerage_api_src_brokerage_proto_rawDescGZIP() []byte {
	file_services_brokerage_api_src_brokerage_proto_rawDescOnce.Do(func() {
		file_services_brokerage_api_src_brokerage_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_brokerage_api_src_brokerage_proto_rawDescData)
	})
	return file_services_brokerage_api_src_brokerage_proto_rawDescData
}

var file_services_brokerage_api_src_brokerage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_brokerage_api_src_brokerage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_brokerage_api_src_brokerage_proto_goTypes = []interface{}{
	(Names)(0),                      // 0: brokerageApi.Names
	(*Brokerage)(nil),               // 1: brokerageApi.Brokerage
	(*GetBrokerage)(nil),            // 2: brokerageApi.GetBrokerage
	(*BrokerageIDReq)(nil),          // 3: brokerageApi.BrokerageIDReq
	(*api.Auth)(nil),                // 4: api.Auth
	(api.StatusType)(0),             // 5: api.StatusType
	(*api.StatusChangeRequest)(nil), // 6: api.StatusChangeRequest
	(*api.Void)(nil),                // 7: api.Void
	(*api.Status)(nil),              // 8: api.Status
}
var file_services_brokerage_api_src_brokerage_proto_depIdxs = []int32{
	4, // 0: brokerageApi.Brokerage.Auth:type_name -> api.Auth
	0, // 1: brokerageApi.Brokerage.Name:type_name -> brokerageApi.Names
	5, // 2: brokerageApi.Brokerage.Status:type_name -> api.StatusType
	1, // 3: brokerageApi.BrokerageService.Add:input_type -> brokerageApi.Brokerage
	3, // 4: brokerageApi.BrokerageService.Get:input_type -> brokerageApi.BrokerageIDReq
	3, // 5: brokerageApi.BrokerageService.Delete:input_type -> brokerageApi.BrokerageIDReq
	6, // 6: brokerageApi.BrokerageService.ChangeStatus:input_type -> api.StatusChangeRequest
	1, // 7: brokerageApi.BrokerageService.Add:output_type -> brokerageApi.Brokerage
	2, // 8: brokerageApi.BrokerageService.Get:output_type -> brokerageApi.GetBrokerage
	7, // 9: brokerageApi.BrokerageService.Delete:output_type -> api.Void
	8, // 10: brokerageApi.BrokerageService.ChangeStatus:output_type -> api.Status
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_brokerage_api_src_brokerage_proto_init() }
func file_services_brokerage_api_src_brokerage_proto_init() {
	if File_services_brokerage_api_src_brokerage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_brokerage_api_src_brokerage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Brokerage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_brokerage_api_src_brokerage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBrokerage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_brokerage_api_src_brokerage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrokerageIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_brokerage_api_src_brokerage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_brokerage_api_src_brokerage_proto_goTypes,
		DependencyIndexes: file_services_brokerage_api_src_brokerage_proto_depIdxs,
		EnumInfos:         file_services_brokerage_api_src_brokerage_proto_enumTypes,
		MessageInfos:      file_services_brokerage_api_src_brokerage_proto_msgTypes,
	}.Build()
	File_services_brokerage_api_src_brokerage_proto = out.File
	file_services_brokerage_api_src_brokerage_proto_rawDesc = nil
	file_services_brokerage_api_src_brokerage_proto_goTypes = nil
	file_services_brokerage_api_src_brokerage_proto_depIdxs = nil
}
