// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: services/brokerage/api/src/candle.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Candle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"updated_at"
	UpdatedAt int64 `protobuf:"varint,1,opt,name=UpdatedAt,proto3" json:"updated_at"`
	// @inject_tag: json:"created_at"
	CreatedAt int64 `protobuf:"varint,2,opt,name=CreatedAt,proto3" json:"created_at"`
	// @inject_tag: json:"volume"
	Volume float64 `protobuf:"fixed64,3,opt,name=Volume,proto3" json:"volume"`
	// @inject_tag: json:"amount"
	Amount float64 `protobuf:"fixed64,4,opt,name=Amount,proto3" json:"amount"`
	// @inject_tag: json:"close"
	Close float64 `protobuf:"fixed64,5,opt,name=Close,proto3" json:"close"`
	// @inject_tag: json:"open"
	Open float64 `protobuf:"fixed64,6,opt,name=Open,proto3" json:"open"`
	// @inject_tag: json:"time"
	Time int64 `protobuf:"varint,7,opt,name=Time,proto3" json:"time"`
	// @inject_tag: json:"high"
	High float64 `protobuf:"fixed64,8,opt,name=High,proto3" json:"high"`
	// @inject_tag: json:"low"
	Low float64 `protobuf:"fixed64,9,opt,name=Low,proto3" json:"low"`
	// @inject_tag: json:"id"
	ID string `protobuf:"bytes,10,opt,name=ID,proto3" json:"id"`
}

func (x *Candle) Reset() {
	*x = Candle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_candle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_candle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_candle_proto_rawDescGZIP(), []int{0}
}

func (x *Candle) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Candle) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Candle) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Candle) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Candle) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Candle) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Candle) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Candle) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Candle) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Candle) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type OhlcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"resolution"
	Resolution *Resolution `protobuf:"bytes,1,opt,name=Resolution,proto3" json:"resolution"`
	// @inject_tag: json:"market"
	Market *Market `protobuf:"bytes,2,opt,name=Market,proto3" json:"market"`
	// @inject_tag: json:"from"
	From int64 `protobuf:"varint,3,opt,name=From,proto3" json:"from"`
	// @inject_tag: json:"to"
	To int64 `protobuf:"varint,4,opt,name=To,proto3" json:"to"`
}

func (x *OhlcRequest) Reset() {
	*x = OhlcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_candle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OhlcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OhlcRequest) ProtoMessage() {}

func (x *OhlcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_candle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OhlcRequest.ProtoReflect.Descriptor instead.
func (*OhlcRequest) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_candle_proto_rawDescGZIP(), []int{1}
}

func (x *OhlcRequest) GetResolution() *Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *OhlcRequest) GetMarket() *Market {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *OhlcRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *OhlcRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type Candles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"candles"
	Candles []*Candle `protobuf:"bytes,1,rep,name=Candles,proto3" json:"candles"`
}

func (x *Candles) Reset() {
	*x = Candles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_candle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Candles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candles) ProtoMessage() {}

func (x *Candles) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_candle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candles.ProtoReflect.Descriptor instead.
func (*Candles) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_candle_proto_rawDescGZIP(), []int{2}
}

func (x *Candles) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

var File_services_brokerage_api_src_candle_proto protoreflect.FileDescriptor

var file_services_brokerage_api_src_candle_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x1a, 0x2b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x01,
	0x0a, 0x06, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4f, 0x70,
	0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x69, 0x67, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x48, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x77, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x4c, 0x6f, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x99, 0x01, 0x0a, 0x0b, 0x4f, 0x68, 0x6c,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70,
	0x69, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x54, 0x6f, 0x22, 0x39, 0x0a, 0x07, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x12,
	0x2e, 0x0a, 0x07, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e,
	0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x07, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x32,
	0x49, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x38, 0x0a, 0x04, 0x4f, 0x48, 0x4c, 0x43, 0x12, 0x19, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x4f, 0x68, 0x6c, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41,
	0x70, 0x69, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x72, 0x4e, 0x6f, 0x62, 0x6f, 0x64,
	0x79, 0x39, 0x35, 0x2f, 0x47, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_brokerage_api_src_candle_proto_rawDescOnce sync.Once
	file_services_brokerage_api_src_candle_proto_rawDescData = file_services_brokerage_api_src_candle_proto_rawDesc
)

func file_services_brokerage_api_src_candle_proto_rawDescGZIP() []byte {
	file_services_brokerage_api_src_candle_proto_rawDescOnce.Do(func() {
		file_services_brokerage_api_src_candle_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_brokerage_api_src_candle_proto_rawDescData)
	})
	return file_services_brokerage_api_src_candle_proto_rawDescData
}

var file_services_brokerage_api_src_candle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_brokerage_api_src_candle_proto_goTypes = []interface{}{
	(*Candle)(nil),      // 0: brokerageApi.Candle
	(*OhlcRequest)(nil), // 1: brokerageApi.OhlcRequest
	(*Candles)(nil),     // 2: brokerageApi.Candles
	(*Resolution)(nil),  // 3: brokerageApi.Resolution
	(*Market)(nil),      // 4: brokerageApi.Market
}
var file_services_brokerage_api_src_candle_proto_depIdxs = []int32{
	3, // 0: brokerageApi.OhlcRequest.Resolution:type_name -> brokerageApi.Resolution
	4, // 1: brokerageApi.OhlcRequest.Market:type_name -> brokerageApi.Market
	0, // 2: brokerageApi.Candles.Candles:type_name -> brokerageApi.Candle
	1, // 3: brokerageApi.CandleService.OHLC:input_type -> brokerageApi.OhlcRequest
	2, // 4: brokerageApi.CandleService.OHLC:output_type -> brokerageApi.Candles
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_brokerage_api_src_candle_proto_init() }
func file_services_brokerage_api_src_candle_proto_init() {
	if File_services_brokerage_api_src_candle_proto != nil {
		return
	}
	file_services_brokerage_api_src_resolution_proto_init()
	file_services_brokerage_api_src_market_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_brokerage_api_src_candle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Candle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_brokerage_api_src_candle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OhlcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_brokerage_api_src_candle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Candles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_brokerage_api_src_candle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_brokerage_api_src_candle_proto_goTypes,
		DependencyIndexes: file_services_brokerage_api_src_candle_proto_depIdxs,
		MessageInfos:      file_services_brokerage_api_src_candle_proto_msgTypes,
	}.Build()
	File_services_brokerage_api_src_candle_proto = out.File
	file_services_brokerage_api_src_candle_proto_rawDesc = nil
	file_services_brokerage_api_src_candle_proto_goTypes = nil
	file_services_brokerage_api_src_candle_proto_depIdxs = nil
}
