// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: services/brokerage/api/src/strategy.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndicatorNames int32

const (
	IndicatorNames_RSI            IndicatorNames = 0
	IndicatorNames_Stochastic     IndicatorNames = 1
	IndicatorNames_MovingAverage  IndicatorNames = 2
	IndicatorNames_BollingerBands IndicatorNames = 3
)

// Enum value maps for IndicatorNames.
var (
	IndicatorNames_name = map[int32]string{
		0: "RSI",
		1: "Stochastic",
		2: "MovingAverage",
		3: "BollingerBands",
	}
	IndicatorNames_value = map[string]int32{
		"RSI":            0,
		"Stochastic":     1,
		"MovingAverage":  2,
		"BollingerBands": 3,
	}
)

func (x IndicatorNames) Enum() *IndicatorNames {
	p := new(IndicatorNames)
	*p = x
	return p
}

func (x IndicatorNames) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndicatorNames) Descriptor() protoreflect.EnumDescriptor {
	return file_services_brokerage_api_src_strategy_proto_enumTypes[0].Descriptor()
}

func (IndicatorNames) Type() protoreflect.EnumType {
	return &file_services_brokerage_api_src_strategy_proto_enumTypes[0]
}

func (x IndicatorNames) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndicatorNames.Descriptor instead.
func (IndicatorNames) EnumDescriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_strategy_proto_rawDescGZIP(), []int{0}
}

type Strategy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
	// @inject_tag: json:"indicators"
	Indicators []*Indicator `protobuf:"bytes,2,rep,name=Indicators,proto3" json:"indicators"`
	// @inject_tag: json:"created_at,omitempty"
	CreatedAt int64 `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"created_at,omitempty"`
	// @inject_tag: json:"updated_at,omitempty"
	UpdatedAt int64 `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Strategy) Reset() {
	*x = Strategy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_strategy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strategy) ProtoMessage() {}

func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_strategy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *Strategy) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Strategy) GetIndicators() []*Indicator {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *Strategy) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Strategy) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Indicator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"name"
	Name IndicatorNames `protobuf:"varint,1,opt,name=Name,proto3,enum=brokerageApi.IndicatorNames" json:"name"`
	// @inject_tag: json:"configs"
	Configs []byte `protobuf:"bytes,2,opt,name=Configs,proto3" json:"configs"`
}

func (x *Indicator) Reset() {
	*x = Indicator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_strategy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Indicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indicator) ProtoMessage() {}

func (x *Indicator) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_strategy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indicator.ProtoReflect.Descriptor instead.
func (*Indicator) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *Indicator) GetName() IndicatorNames {
	if x != nil {
		return x.Name
	}
	return IndicatorNames_RSI
}

func (x *Indicator) GetConfigs() []byte {
	if x != nil {
		return x.Configs
	}
	return nil
}

type CreateStrategyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"indicators"
	Indicators []*Indicator `protobuf:"bytes,1,rep,name=Indicators,proto3" json:"indicators"`
}

func (x *CreateStrategyReq) Reset() {
	*x = CreateStrategyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_strategy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStrategyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStrategyReq) ProtoMessage() {}

func (x *CreateStrategyReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_strategy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStrategyReq.ProtoReflect.Descriptor instead.
func (*CreateStrategyReq) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStrategyReq) GetIndicators() []*Indicator {
	if x != nil {
		return x.Indicators
	}
	return nil
}

type ReturnStrategyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"id"`
}

func (x *ReturnStrategyReq) Reset() {
	*x = ReturnStrategyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_brokerage_api_src_strategy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnStrategyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnStrategyReq) ProtoMessage() {}

func (x *ReturnStrategyReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_brokerage_api_src_strategy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnStrategyReq.ProtoReflect.Descriptor instead.
func (*ReturnStrategyReq) Descriptor() ([]byte, []int) {
	return file_services_brokerage_api_src_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *ReturnStrategyReq) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_services_brokerage_api_src_strategy_proto protoreflect.FileDescriptor

var file_services_brokerage_api_src_strategy_proto_rawDesc = []byte{
	0x0a, 0x29, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x22, 0x8f, 0x01, 0x0a, 0x08, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12, 0x37, 0x0a, 0x0a, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x0a, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x57, 0x0a, 0x09, 0x49,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x30, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x73, 0x22, 0x4c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x0a, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x2a, 0x50, 0x0a, 0x0e, 0x49, 0x6e, 0x64, 0x69, 0x63,
	0x61, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x53, 0x49,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x63, 0x68, 0x61, 0x73, 0x74, 0x69, 0x63,
	0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x41, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x6f, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x42, 0x61, 0x6e, 0x64, 0x73, 0x10, 0x03, 0x32, 0x97, 0x01, 0x0a, 0x0f, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a,
	0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x12, 0x41, 0x0a, 0x06, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x1f, 0x2e, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x61, 0x67, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x72, 0x4e, 0x6f, 0x62, 0x6f, 0x64, 0x79, 0x39, 0x35, 0x2f, 0x47, 0x61, 0x74,
	0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_brokerage_api_src_strategy_proto_rawDescOnce sync.Once
	file_services_brokerage_api_src_strategy_proto_rawDescData = file_services_brokerage_api_src_strategy_proto_rawDesc
)

func file_services_brokerage_api_src_strategy_proto_rawDescGZIP() []byte {
	file_services_brokerage_api_src_strategy_proto_rawDescOnce.Do(func() {
		file_services_brokerage_api_src_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_brokerage_api_src_strategy_proto_rawDescData)
	})
	return file_services_brokerage_api_src_strategy_proto_rawDescData
}

var file_services_brokerage_api_src_strategy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_brokerage_api_src_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_brokerage_api_src_strategy_proto_goTypes = []interface{}{
	(IndicatorNames)(0),       // 0: brokerageApi.IndicatorNames
	(*Strategy)(nil),          // 1: brokerageApi.Strategy
	(*Indicator)(nil),         // 2: brokerageApi.Indicator
	(*CreateStrategyReq)(nil), // 3: brokerageApi.CreateStrategyReq
	(*ReturnStrategyReq)(nil), // 4: brokerageApi.ReturnStrategyReq
}
var file_services_brokerage_api_src_strategy_proto_depIdxs = []int32{
	2, // 0: brokerageApi.Strategy.Indicators:type_name -> brokerageApi.Indicator
	0, // 1: brokerageApi.Indicator.Name:type_name -> brokerageApi.IndicatorNames
	2, // 2: brokerageApi.CreateStrategyReq.Indicators:type_name -> brokerageApi.Indicator
	3, // 3: brokerageApi.StrategyService.Create:input_type -> brokerageApi.CreateStrategyReq
	4, // 4: brokerageApi.StrategyService.Return:input_type -> brokerageApi.ReturnStrategyReq
	1, // 5: brokerageApi.StrategyService.Create:output_type -> brokerageApi.Strategy
	1, // 6: brokerageApi.StrategyService.Return:output_type -> brokerageApi.Strategy
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_brokerage_api_src_strategy_proto_init() }
func file_services_brokerage_api_src_strategy_proto_init() {
	if File_services_brokerage_api_src_strategy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_brokerage_api_src_strategy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Strategy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_brokerage_api_src_strategy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Indicator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_brokerage_api_src_strategy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStrategyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_brokerage_api_src_strategy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnStrategyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_brokerage_api_src_strategy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_brokerage_api_src_strategy_proto_goTypes,
		DependencyIndexes: file_services_brokerage_api_src_strategy_proto_depIdxs,
		EnumInfos:         file_services_brokerage_api_src_strategy_proto_enumTypes,
		MessageInfos:      file_services_brokerage_api_src_strategy_proto_msgTypes,
	}.Build()
	File_services_brokerage_api_src_strategy_proto = out.File
	file_services_brokerage_api_src_strategy_proto_rawDesc = nil
	file_services_brokerage_api_src_strategy_proto_goTypes = nil
	file_services_brokerage_api_src_strategy_proto_depIdxs = nil
}
