if [ "${1}" = "" ]; then
  echo "formatting hole project"
#  golangci-lint run ./services/"${1}"/...
  go fmt ./...
  go vet ./...
else
#  golangci-lint run ./services/"${1}"/...
  go fmt ./services/"${1}"/...
  go vet ./services/"${1}"/...
fi